### ISSUE TITLE
FIX: Uppercase issue of Display Character from A to Z Using Loop

### ISSUE THREAD

**Issue by apneduniya** [parthasdey2304/end-semester-c-programming-practise#1]
![image](https://github.com/parthasdey2304/end-semester-c-programming-practise/assets/113763427/b3e2f666-b7a1-41eb-b8a4-36447fa88094)

Here you have said how to print **uppercase** English alphabet but both here and in code print it in _lowercase_. We need to update the code by adding `toupper()` both in file and its respective [README.md](https://github.com/parthasdey2304/end-semester-c-programming-practise/blob/main/assignments/README.md#5-display-character-from-a-to-z-using-loop) file.

If you want I would be happy to get this issue assigned to me :upside_down_face:

**Comment by parthasdey2304** [comment]
Thanks for pointing out the bug @apneduniya I'll fix it soon.
